# This workflow will use Docker Compose to run end-to-end tests
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: application - continuous integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t my-app-image ./backend

    - name: Run e2e tests using Docker Compose
      run: |
        docker-compose -f docker-compose.test.yml up -d
        sleep 5
        docker-compose -f docker-compose.test.yml exec -T <service-name> npm run db:test:setup
        docker-compose -f docker-compose.test.yml exec -T <service-name> npm run test:e2e
        docker-compose -f docker-compose.test.yml down
      # Replace <service-name> with the name of the service defined in your docker-compose.test.yml
